const { _electron: electron } = require('@playwright/test');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../../work/ui-test');
async function main() {
  await fs.mkdir(root, { recursive: true });
  const application = await electron.launch({ args: [path.resolve(__dirname, '..')], env: { ...process.env, ONE_LINK_TEST_PROFILE: path.join(root, 'profile') } });
  try {
    const page = await application.firstWindow(); const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await page.getByRole('heading', { name: '기기를 연결하고, 바로 공유하세요.' }).waitFor();
    await page.emulateMedia({ colorScheme: 'light' });
    await page.evaluate(() => document.fonts.ready);
    assert.equal(await page.evaluate(() => document.fonts.check('700 29px Rajdhani')), true);
    assert.equal(await page.evaluate(() => document.fonts.check('400 14px Pretendard')), true);
    assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()), '#d35400');
    await page.getByRole('button', { name: 'ONE LINK 정보' }).click();
    await page.locator('.about-dialog').waitFor();
    assert.match(await page.locator('.about-dialog').innerText(), /Unknown/);
    assert.ok((await page.locator('.about-dialog').innerText()).includes(require('../package.json').version));
    await page.screenshot({ path: path.resolve(__dirname, '../../ONE-LINK-about.png') });
    await application.evaluate(({ shell }) => { shell.openExternal = async url => { global.__brandUrl = url; }; });
    await page.locator('[data-action="openBrandChannel"]').click();
    assert.equal(await application.evaluate(() => global.__brandUrl), 'https://www.youtube.com/@unknown8563');
    await page.locator('[data-action="fontLicenses"]').click();
    await page.locator('.license-dialog').waitFor();
    assert.match(await page.locator('.license-dialog').textContent(), /SIL OPEN FONT LICENSE/);
    await page.locator('.license-dialog [data-action="about"]').click();
    await page.getByRole('button', { name: '확인', exact: true }).click();
    await page.emulateMedia({ colorScheme: 'dark' });
    assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()), '#111111');
    await page.emulateMedia({ colorScheme: 'light' });
    await page.getByRole('button', { name: '내 공유 폴더', exact: false }).click();
    await page.getByRole('heading', { name: '내 공유 폴더', exact: true }).waitFor();
    await page.getByRole('button', { name: '＋ 폴더 공유' }).click();
    await page.getByRole('heading', { name: '폴더 공유', exact: true }).waitFor();
    await page.getByRole('button', { name: '닫기', exact: true }).click();
    await page.locator('[data-nav="settings"]').click();
    await page.getByRole('button', { name: '업데이트 확인', exact: true }).waitFor();
    assert.equal((await page.evaluate(() => window.oneLink.command('updateState'))).phase, 'unavailable');
    await page.getByLabel('기기 이름', { exact: true }).fill('ONE LINK 테스트');
    await page.getByRole('button', { name: '저장', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#local-name').textContent === 'ONE LINK 테스트');
    await page.waitForFunction(() => !busy);
    await page.locator('[data-nav="devices"]').click();
    await page.getByRole('button', { name: '＋ 기기 연결', exact: true }).click();
    await page.locator('#manual-host').fill('192.168.1.10');
    await page.getByRole('button', { name: '연결 확인', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('Tailscale 주소만'));
    await page.getByRole('button', { name: '닫기', exact: true }).click();
    await page.locator('[data-nav="history"]').click();
    await page.getByRole('heading', { name: '전송 기록', exact: true }).waitFor();
    await page.locator('[data-nav="devices"]').click();
    await page.evaluate(() => document.querySelector('#toast').classList.add('hidden'));
    await page.screenshot({ path: path.resolve(__dirname, '../../ONE-LINK-preview.png'), fullPage: true });
    assert.deepEqual(errors, []);
    console.log('UI PASS: branding, fonts, About, allowlisted channel, font licenses, light/dark, navigation, sharing, settings and history.');
  } finally { await application.close(); }
}
main().catch(e => { console.error(e); process.exitCode = 1; });
